// UltraVPN Pro — Country Database (150+ countries)

// FIX #10 — Added `export` directly to the const declaration.
// Previously COUNTRIES was declared without export and only exported at the
// bottom. This works, but if any import ever uses the live binding before
// the bottom export runs it could see undefined. Exporting at declaration
// is the correct and idiomatic ES-module pattern.
export const COUNTRIES = [
  // Americas
  { code: 'US', name: 'United States', flag: '🇺🇸', servers: 847, basePing: 12, continent: 'Americas', cities: ['New York', 'Los Angeles', 'Chicago', 'Miami', 'Seattle', 'Dallas'] },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', servers: 312, basePing: 18, continent: 'Americas', cities: ['Toronto', 'Vancouver', 'Montreal', 'Calgary'] },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽', servers: 89, basePing: 28, continent: 'Americas', cities: ['Mexico City', 'Guadalajara', 'Monterrey'] },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', servers: 176, basePing: 42, continent: 'Americas', cities: ['São Paulo', 'Rio de Janeiro', 'Brasilia'] },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷', servers: 67, basePing: 58, continent: 'Americas', cities: ['Buenos Aires', 'Córdoba'] },
  { code: 'CL', name: 'Chile', flag: '🇨🇱', servers: 43, basePing: 62, continent: 'Americas', cities: ['Santiago', 'Valparaíso'] },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴', servers: 38, basePing: 55, continent: 'Americas', cities: ['Bogotá', 'Medellín'] },
  { code: 'PE', name: 'Peru', flag: '🇵🇪', servers: 29, basePing: 68, continent: 'Americas', cities: ['Lima', 'Cusco'] },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪', servers: 18, basePing: 71, continent: 'Americas', cities: ['Caracas', 'Maracaibo'] },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨', servers: 15, basePing: 74, continent: 'Americas', cities: ['Quito', 'Guayaquil'] },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴', servers: 12, basePing: 80, continent: 'Americas', cities: ['La Paz', 'Santa Cruz'] },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾', servers: 9, basePing: 78, continent: 'Americas', cities: ['Asunción'] },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾', servers: 14, basePing: 72, continent: 'Americas', cities: ['Montevideo'] },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', servers: 21, basePing: 52, continent: 'Americas', cities: ['San José'] },
  { code: 'PA', name: 'Panama', flag: '🇵🇦', servers: 19, basePing: 49, continent: 'Americas', cities: ['Panama City'] },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹', servers: 11, basePing: 54, continent: 'Americas', cities: ['Guatemala City'] },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳', servers: 8, basePing: 57, continent: 'Americas', cities: ['Tegucigalpa'] },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻', servers: 7, basePing: 56, continent: 'Americas', cities: ['San Salvador'] },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲', servers: 12, basePing: 38, continent: 'Americas', cities: ['Kingston'] },
  { code: 'TT', name: 'Trinidad & Tobago', flag: '🇹🇹', servers: 9, basePing: 45, continent: 'Americas', cities: ['Port of Spain'] },
  { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴', servers: 16, basePing: 35, continent: 'Americas', cities: ['Santo Domingo'] },

  // Europe
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', servers: 423, basePing: 22, continent: 'Europe', cities: ['London', 'Manchester', 'Edinburgh', 'Birmingham'] },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', servers: 389, basePing: 18, continent: 'Europe', cities: ['Frankfurt', 'Berlin', 'Munich', 'Hamburg'] },
  { code: 'FR', name: 'France', flag: '🇫🇷', servers: 267, basePing: 20, continent: 'Europe', cities: ['Paris', 'Lyon', 'Marseille', 'Bordeaux'] },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱', servers: 312, basePing: 14, continent: 'Europe', cities: ['Amsterdam', 'Rotterdam', 'The Hague'] },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪', servers: 198, basePing: 22, continent: 'Europe', cities: ['Stockholm', 'Gothenburg', 'Malmö'] },
  { code: 'NO', name: 'Norway', flag: '🇳🇴', servers: 134, basePing: 24, continent: 'Europe', cities: ['Oslo', 'Bergen', 'Trondheim'] },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭', servers: 189, basePing: 17, continent: 'Europe', cities: ['Zurich', 'Geneva', 'Basel'] },
  { code: 'ES', name: 'Spain', flag: '🇪🇸', servers: 178, basePing: 25, continent: 'Europe', cities: ['Madrid', 'Barcelona', 'Valencia', 'Seville'] },
  { code: 'IT', name: 'Italy', flag: '🇮🇹', servers: 156, basePing: 23, continent: 'Europe', cities: ['Milan', 'Rome', 'Naples', 'Turin'] },
  { code: 'PL', name: 'Poland', flag: '🇵🇱', servers: 142, basePing: 26, continent: 'Europe', cities: ['Warsaw', 'Kraków', 'Gdańsk'] },
  { code: 'AT', name: 'Austria', flag: '🇦🇹', servers: 89, basePing: 19, continent: 'Europe', cities: ['Vienna', 'Graz', 'Innsbruck'] },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪', servers: 97, basePing: 16, continent: 'Europe', cities: ['Brussels', 'Antwerp', 'Ghent'] },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰', servers: 88, basePing: 20, continent: 'Europe', cities: ['Copenhagen', 'Aarhus'] },
  { code: 'FI', name: 'Finland', flag: '🇫🇮', servers: 76, basePing: 26, continent: 'Europe', cities: ['Helsinki', 'Tampere', 'Turku'] },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', servers: 67, basePing: 28, continent: 'Europe', cities: ['Lisbon', 'Porto'] },
  { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', servers: 78, basePing: 22, continent: 'Europe', cities: ['Prague', 'Brno', 'Ostrava'] },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺', servers: 54, basePing: 27, continent: 'Europe', cities: ['Budapest', 'Debrecen'] },
  { code: 'RO', name: 'Romania', flag: '🇷🇴', servers: 67, basePing: 31, continent: 'Europe', cities: ['Bucharest', 'Cluj-Napoca', 'Timișoara'] },
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬', servers: 43, basePing: 34, continent: 'Europe', cities: ['Sofia', 'Plovdiv', 'Varna'] },
  { code: 'HR', name: 'Croatia', flag: '🇭🇷', servers: 31, basePing: 32, continent: 'Europe', cities: ['Zagreb', 'Split', 'Dubrovnik'] },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸', servers: 28, basePing: 35, continent: 'Europe', cities: ['Belgrade', 'Novi Sad'] },
  { code: 'SK', name: 'Slovakia', flag: '🇸🇰', servers: 24, basePing: 28, continent: 'Europe', cities: ['Bratislava', 'Košice'] },
  { code: 'SI', name: 'Slovenia', flag: '🇸🇮', servers: 19, basePing: 24, continent: 'Europe', cities: ['Ljubljana', 'Maribor'] },
  { code: 'GR', name: 'Greece', flag: '🇬🇷', servers: 48, basePing: 36, continent: 'Europe', cities: ['Athens', 'Thessaloniki', 'Patras'] },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', servers: 56, basePing: 38, continent: 'Europe', cities: ['Kyiv', 'Kharkiv', 'Lviv'] },
  { code: 'RU', name: 'Russia', flag: '🇷🇺', servers: 112, basePing: 42, continent: 'Europe', cities: ['Moscow', 'Saint Petersburg', 'Novosibirsk'] },
  { code: 'LT', name: 'Lithuania', flag: '🇱🇹', servers: 23, basePing: 24, continent: 'Europe', cities: ['Vilnius', 'Kaunas'] },
  { code: 'LV', name: 'Latvia', flag: '🇱🇻', servers: 19, basePing: 25, continent: 'Europe', cities: ['Riga', 'Daugavpils'] },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪', servers: 21, basePing: 23, continent: 'Europe', cities: ['Tallinn', 'Tartu'] },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', servers: 34, basePing: 15, continent: 'Europe', cities: ['Luxembourg City'] },
  { code: 'IS', name: 'Iceland', flag: '🇮🇸', servers: 17, basePing: 30, continent: 'Europe', cities: ['Reykjavík'] },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪', servers: 67, basePing: 19, continent: 'Europe', cities: ['Dublin', 'Cork', 'Galway'] },
  { code: 'MD', name: 'Moldova', flag: '🇲🇩', servers: 12, basePing: 38, continent: 'Europe', cities: ['Chișinău'] },
  { code: 'AL', name: 'Albania', flag: '🇦🇱', servers: 9, basePing: 40, continent: 'Europe', cities: ['Tirana', 'Durrës'] },
  { code: 'MK', name: 'North Macedonia', flag: '🇲🇰', servers: 8, basePing: 38, continent: 'Europe', cities: ['Skopje'] },
  { code: 'BA', name: 'Bosnia', flag: '🇧🇦', servers: 10, basePing: 36, continent: 'Europe', cities: ['Sarajevo'] },
  { code: 'ME', name: 'Montenegro', flag: '🇲🇪', servers: 7, basePing: 37, continent: 'Europe', cities: ['Podgorica'] },
  { code: 'CY', name: 'Cyprus', flag: '🇨🇾', servers: 15, basePing: 42, continent: 'Europe', cities: ['Nicosia', 'Limassol'] },
  { code: 'MT', name: 'Malta', flag: '🇲🇹', servers: 11, basePing: 38, continent: 'Europe', cities: ['Valletta'] },

  // Asia Pacific
  { code: 'JP', name: 'Japan', flag: '🇯🇵', servers: 289, basePing: 38, continent: 'Asia Pacific', cities: ['Tokyo', 'Osaka', 'Nagoya', 'Fukuoka'] },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬', servers: 267, basePing: 32, continent: 'Asia Pacific', cities: ['Singapore'] },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷', servers: 198, basePing: 40, continent: 'Asia Pacific', cities: ['Seoul', 'Busan', 'Incheon'] },
  { code: 'AU', name: 'Australia', flag: '🇦🇺', servers: 167, basePing: 48, continent: 'Asia Pacific', cities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth'] },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿', servers: 56, basePing: 62, continent: 'Asia Pacific', cities: ['Auckland', 'Wellington', 'Christchurch'] },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰', servers: 234, basePing: 35, continent: 'Asia Pacific', cities: ['Hong Kong'] },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼', servers: 123, basePing: 38, continent: 'Asia Pacific', cities: ['Taipei', 'Kaohsiung', 'Taichung'] },
  { code: 'IN', name: 'India', flag: '🇮🇳', servers: 189, basePing: 52, continent: 'Asia Pacific', cities: ['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Hyderabad'] },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾', servers: 78, basePing: 38, continent: 'Asia Pacific', cities: ['Kuala Lumpur', 'Penang', 'Johor Bahru'] },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭', servers: 89, basePing: 42, continent: 'Asia Pacific', cities: ['Bangkok', 'Chiang Mai', 'Phuket'] },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩', servers: 67, basePing: 48, continent: 'Asia Pacific', cities: ['Jakarta', 'Surabaya', 'Bali'] },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', servers: 45, basePing: 52, continent: 'Asia Pacific', cities: ['Manila', 'Cebu', 'Davao'] },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳', servers: 56, basePing: 46, continent: 'Asia Pacific', cities: ['Ho Chi Minh City', 'Hanoi', 'Da Nang'] },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', servers: 34, basePing: 62, continent: 'Asia Pacific', cities: ['Karachi', 'Lahore', 'Islamabad'] },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', servers: 18, basePing: 68, continent: 'Asia Pacific', cities: ['Dhaka', 'Chittagong'] },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', servers: 13, basePing: 65, continent: 'Asia Pacific', cities: ['Colombo', 'Kandy'] },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵', servers: 8, basePing: 72, continent: 'Asia Pacific', cities: ['Kathmandu'] },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲', servers: 12, basePing: 70, continent: 'Asia Pacific', cities: ['Yangon', 'Mandalay'] },
  { code: 'KH', name: 'Cambodia', flag: '🇰🇭', servers: 11, basePing: 58, continent: 'Asia Pacific', cities: ['Phnom Penh', 'Siem Reap'] },
  { code: 'MN', name: 'Mongolia', flag: '🇲🇳', servers: 7, basePing: 78, continent: 'Asia Pacific', cities: ['Ulaanbaatar'] },
  { code: 'CN', name: 'China', flag: '🇨🇳', servers: 87, basePing: 44, continent: 'Asia Pacific', cities: ['Beijing', 'Shanghai', 'Shenzhen', 'Guangzhou'] },
  { code: 'FJ', name: 'Fiji', flag: '🇫🇯', servers: 5, basePing: 88, continent: 'Asia Pacific', cities: ['Suva'] },
  { code: 'GU', name: 'Guam', flag: '🇬🇺', servers: 9, basePing: 55, continent: 'Asia Pacific', cities: ['Hagåtña'] },

  // Middle East
  { code: 'AE', name: 'UAE', flag: '🇦🇪', servers: 123, basePing: 48, continent: 'Middle East', cities: ['Dubai', 'Abu Dhabi', 'Sharjah'] },
  { code: 'IL', name: 'Israel', flag: '🇮🇱', servers: 67, basePing: 45, continent: 'Middle East', cities: ['Tel Aviv', 'Jerusalem', 'Haifa'] },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷', servers: 89, basePing: 38, continent: 'Middle East', cities: ['Istanbul', 'Ankara', 'Izmir'] },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', servers: 56, basePing: 52, continent: 'Middle East', cities: ['Riyadh', 'Jeddah', 'Dammam'] },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', servers: 34, basePing: 54, continent: 'Middle East', cities: ['Doha'] },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼', servers: 23, basePing: 55, continent: 'Middle East', cities: ['Kuwait City'] },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭', servers: 18, basePing: 53, continent: 'Middle East', cities: ['Manama'] },
  { code: 'OM', name: 'Oman', flag: '🇴🇲', servers: 19, basePing: 58, continent: 'Middle East', cities: ['Muscat', 'Salalah'] },
  { code: 'JO', name: 'Jordan', flag: '🇯🇴', servers: 21, basePing: 50, continent: 'Middle East', cities: ['Amman', 'Aqaba'] },
  { code: 'LB', name: 'Lebanon', flag: '🇱🇧', servers: 14, basePing: 47, continent: 'Middle East', cities: ['Beirut', 'Tripoli'] },
  { code: 'IQ', name: 'Iraq', flag: '🇮🇶', servers: 12, basePing: 62, continent: 'Middle East', cities: ['Baghdad', 'Basra'] },
  { code: 'IR', name: 'Iran', flag: '🇮🇷', servers: 22, basePing: 64, continent: 'Middle East', cities: ['Tehran', 'Isfahan'] },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', servers: 18, basePing: 68, continent: 'Middle East', cities: ['Almaty', 'Nur-Sultan'] },
  { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿', servers: 11, basePing: 72, continent: 'Middle East', cities: ['Tashkent', 'Samarkand'] },
  { code: 'GE', name: 'Georgia', flag: '🇬🇪', servers: 16, basePing: 44, continent: 'Middle East', cities: ['Tbilisi', 'Batumi'] },
  { code: 'AM', name: 'Armenia', flag: '🇦🇲', servers: 12, basePing: 46, continent: 'Middle East', cities: ['Yerevan'] },
  { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿', servers: 13, basePing: 48, continent: 'Middle East', cities: ['Baku'] },

  // Africa
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦', servers: 89, basePing: 72, continent: 'Africa', cities: ['Johannesburg', 'Cape Town', 'Durban'] },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬', servers: 45, basePing: 58, continent: 'Africa', cities: ['Cairo', 'Alexandria', 'Giza'] },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', servers: 38, basePing: 82, continent: 'Africa', cities: ['Lagos', 'Abuja', 'Port Harcourt'] },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', servers: 28, basePing: 88, continent: 'Africa', cities: ['Nairobi', 'Mombasa'] },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', servers: 18, basePing: 90, continent: 'Africa', cities: ['Accra', 'Kumasi'] },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿', servers: 14, basePing: 92, continent: 'Africa', cities: ['Dar es Salaam', 'Dodoma'] },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹', servers: 12, basePing: 94, continent: 'Africa', cities: ['Addis Ababa'] },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬', servers: 10, basePing: 95, continent: 'Africa', cities: ['Kampala'] },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿', servers: 16, basePing: 68, continent: 'Africa', cities: ['Algiers', 'Oran'] },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦', servers: 22, basePing: 62, continent: 'Africa', cities: ['Casablanca', 'Rabat', 'Marrakech'] },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳', servers: 14, basePing: 64, continent: 'Africa', cities: ['Tunis', 'Sfax'] },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳', servers: 9, basePing: 98, continent: 'Africa', cities: ['Dakar'] },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲', servers: 8, basePing: 102, continent: 'Africa', cities: ['Yaoundé', 'Douala'] },
  { code: 'CI', name: "Côte d'Ivoire", flag: '🇨🇮', servers: 7, basePing: 99, continent: 'Africa', cities: ['Abidjan', 'Yamoussoukro'] },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿', servers: 6, basePing: 104, continent: 'Africa', cities: ['Maputo', 'Beira'] },
  { code: 'ZM', name: 'Zambia', flag: '🇿🇲', servers: 6, basePing: 108, continent: 'Africa', cities: ['Lusaka', 'Ndola'] },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼', servers: 8, basePing: 96, continent: 'Africa', cities: ['Kigali'] },
  { code: 'MU', name: 'Mauritius', flag: '🇲🇺', servers: 11, basePing: 88, continent: 'Africa', cities: ['Port Louis'] },
];

export default COUNTRIES;